version: '3'

services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: gustavosilvani/php
    container_name: php
    networks:
      - phpnet
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=randomuser
      - DB_USERNAME=root
      - DB_PASSWORD=123456a

  mysql:
    image: mysql
    container_name: mysql-php
    networks:
      - phpnet
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456a
      MYSQL_DATABASE: randomuser

networks:
  phpnet:
    driver: bridge